FROM node:16

# Create destination directory
RUN mkdir /app
WORKDIR /app

# Копируем оставшиеся файлы проекта в контейнер
COPY . .

# Set environment variables
ENV NODE_ENV=production
RUN yarn install --frozen-lockfile
RUN yarn build-server


ARG DOCKER_TAG
ENV DOCKER_TAG $DOCKER_TAG

# Start the route cache updater service
CMD [ "node", "./lib/server/services/apiV2Service/routeCacheUpdater.js" ]
